### ISSUE TITLE
[Bug] Quick and useful description

### ISSUE THREAD

**Issue by earlhsjks** [ToberoCat/ImprovedFactions#112]
**Describe the bug**
 error encountered while running this command 

**Error log from console**
https://mclo.gs/4Gy5600#L1466

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Plugin: IF
 - Server: Paper 1.20.4

**Additional context**

**Comment by ToberoCat** [comment]
This bug has been fixed in the 2.1.1 build of the plugin
