### ISSUE TITLE
[Suggestion] Add more power placeholders

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions#132]
**Is your feature request related to a problem? Please describe.**

Since GUI Engine is optional in 2.1.3 there isn't a way of getting power information without it installed.

**Describe the solution you'd like**

Add `factions active accumulation`, `faction inactive accumulation` and `factions claim upkeep cost`

**Describe alternatives you've considered**

**Additional context**

**Comment by ToberoCat** [comment]
New power placeholders will be available in 2.1.3

**Comment by ToberoCat** [comment]
As far as I know, without gui engine, it should still display the same information. But instead of an gui, it will be a simple key - value list.
