### ISSUE TITLE
[Bug] Can't set factions home

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions#133]
**Describe the bug**

When I run `/f sethome` It just says it can't set the home

**Error log from console**
None shown

**To Reproduce**
1. Join/create faction
2. Run `/f sethome`
3. See chat error

**Version (please complete the following information):**
 - Plugin: 2.1.3
 - Server: Paper 1.20.1 build 198

**Comment by ToberoCat** [comment]
If I'm correct, this error is just very badly written at telling you: This location is invalid, as the home must be in a claim of yours

**Comment by Josh65-2201** [comment]
I tried doing it in my claim still the same.

**Comment by ToberoCat** [comment]
What's the exact error message?

**Comment by Josh65-2201** [comment]
![image](https://github.com/ToberoCat/ImprovedFactions/assets/26977075/656fc0bb-02d5-4679-a8b2-65131274e86f)

**Comment by ToberoCat** [comment]
Okay, I'll have to try it out myself, as the only reason this message will appear would be when the home isn't in your faction's claim or if the location provided to the system is missing the world, which shouldn't be the issue
