### ISSUE TITLE
[Suggestion] Toggle between Claim Blacklist and Whitelist

### ISSUE THREAD

**Issue by Treblero** [ToberoCat/ImprovedFactions#136]
**Suggestion:**

Being able to utilize a world WHITELIST in the config to only allow land claiming in specified worlds, instead of just a blacklist.

I know there is already a blacklist in the config to deny claiming in certain worlds, but server's that utilize instanced dungeons in separate worlds such as MythicDungeons do not benefit from this, allowing players to claim sections of Dungeons.

**Comment by ToberoCat** [comment]
Thanks for the feedback, I'll add a whitelist option for the next build, as this seems to be a major issue

**Comment by ToberoCat** [comment]
The option is now programmed into the plugin, will be included in the next update
