### ISSUE TITLE
[Bug] Invite GUI doesn't work

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions#148]
**Describe the bug**

There are two issue first is that I have to click back to show the invites, Then when I click on the invite it doesn't do anything and allows moving the items shown.

**Error log from console**
None

**Expected behavior**

- UI should show invites on the first page
- Clicking Invite should join the faction

**Version (please complete the following information):**
 - Plugin: 2.1.3
 - Server: 1.20.1 Paper 198

**Comment by NotAFlyingGoose** [comment]
I'm experiencing the same thing, I get these errors,
```
31.05 07:02:38 [Server] ERROR [ImprovedFactions] faction-detail-page.gui has a invalid component. The given faction name didn't return a faction
31.05 07:02:38 [Server] ERROR [ImprovedFactions] member/member-detail-page.gui has a invalid component. Specified player %member% has never played on the server before
31.05 07:02:38 [Server] ERROR [ImprovedFactions] rank/rank-detail.gui has a invalid component. Rank hasn't been found in the database
```
I already updated to the latest available versions of GuiEngine and Improved Factions on Modrinth

**Comment by TheSteveRizzo** [comment]
I also have this issue, players can not accept invites

**Comment by ToberoCat** [comment]
Gui Module has been removed from the latest dev version, as it's been on life support for a few months now - It'll have a comeback soon, but properly functional
