### ISSUE TITLE
[Bug] Paper 1.19.4+ doesn't support § for color codes

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions#151]
**Describe the bug**
Hex code should be used and is compatible with 1.18+

**Error log from console**
None

**To Reproduce**
1. Download 2.1.3
2. Start server
3. See update notice

**Expected behavior**
Update notice color codes should not show §

**Version (please complete the following information):**
 - Plugin: 2.1.3
 - Server: 1.20.1 Paper 198

**Comment by ToberoCat** [comment]
The colors for the update checker have been removed until the update checker supports hex
