### ISSUE TITLE
[Bug] Claim particle measuring between all players on server

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions#166]
**Describe the bug**

If players are in different worlds partial don't show

**Error log from console**
[error.txt](https://github.com/user-attachments/files/15754216/error.txt)

**Version (please complete the following information):**
 - Plugin: 2.2 beta 1
 - Server: 1.20.1 Paper build 198

**Comment by ToberoCat** [comment]
Will be fixed in 2.2.0
