### ISSUE TITLE
[Bug] Claim protection message shown many times

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions#167]
**Describe the bug**

If I break a block in a claim the message is shown many times rather than once
![image](https://github.com/ToberoCat/ImprovedFactions/assets/26977075/0cd157b6-e66d-43f8-b7a7-833d266912d7)

**Error log from console**
None

**Version (please complete the following information):**
 - Plugin: 2.2 beta 1
 - Server: 1.20.1 Paper build 198

**Comment by ToberoCat** [comment]
Hm, can't seem to reproduce it

**Comment by Josh65-2201** [comment]
This is fixed for me with 2.2.0 beta 2
