### ISSUE TITLE
[Bug] You can place end crystals in claimed chunks

### ISSUE THREAD

**Issue by Specifix5** [ToberoCat/ImprovedFactions#181]
**Describe the bug**
You can place End crystals on exposed obsidians despite the claim protections

**Expected behavior**
Should not be able to place

**Version (please complete the following information):**
 - Plugin: ImprovedFactions 2.2.0
 - Server: Paper 1.20.6 build 149

**Comment by ToberoCat** [comment]
Fixed in latest 2.2.0-dev
