### ISSUE TITLE
[Bug] Long Loadtime

### ISSUE THREAD

**Issue by Duncan-K-Black** [ToberoCat/ImprovedFactions#199]
**Describe the bug**

**Error log from console**

07.07 02:09:46 [Server] [INFO] [ImprovedFactions] [detector] Positions: 20165 Faction | 0 Zone. This might take some time
07.07 02:09:46 [Server] [INFO] [ImprovedFactions] [detector] Finished loading zone positions.

**To Reproduce**
1. Start up server

**Expected behavior**

My server has a super long loadtime of multiple hours once this message is produced.
Note I have tried running this with every other plugin disabled, problem persists.

**Screenshots**

**Version (please complete the following information):**
 - Plugin: ImprovedFactions-2.2.0 
 - Server: 1.21

**Additional context**
N/A

**Comment by Josh65-2201** [comment]
Same as #178

**Comment by ToberoCat** [comment]
This will be fixed in the next build. Your server is taking so long because it's indexing all claims, which takes long when there are many claims.
For speedup, the indexes are cached in the database, which no longer requires reindexing all claims when all of them have been indexed once
