### ISSUE TITLE
[DevReport] /f Invite is broken (Offline mode)

### ISSUE THREAD

**Issue by Specifix5** [ToberoCat/ImprovedFactions#201]
![image](https://github.com/user-attachments/assets/12181935-f320-4dbb-b917-0de90e68b188)
Trying to invite anyone shows that, even a player with a microsoft account
![image](https://github.com/user-attachments/assets/9a2f8864-86a0-4dcb-ae47-f3de0b4c2ec5)

**Comment by ToberoCat** [comment]
fixed with merged pull request
