### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by nososho** [ToberoCat/ImprovedFactions#204]
**Is your feature request related to a problem? Please describe.**
Everyone’s faction chats cannot be viewed by admins or console which makes it hard to moderate.

**Describe the solution you'd like**
Let console always log faction chat messages and add an admin command to display everyones faction chats (something like /f socialspy)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ToberoCat** [comment]
Added /f spy and option logigng all conversations
