### ISSUE TITLE
[Suggestion] Admin command features

### ISSUE THREAD

**Issue by RadiantSoul** [ToberoCat/ImprovedFactions#206]
**faction force leave**
< force a player to leave a faction >

**faction force info <username>**
< gives details about the a players faction, what rank they have, what chunks they have claimed? >

**faction bypass update**
< faction bypass doesnt let you kill mobs set to be protected bt hte plugin >

**Wilderness title cant be disabled**
< wilderness title flashin on screen everytime you leave a faction can get annoying, wouldl ike a config to disable it seperate from the claimed titles >

**faction force claim <faction>**
< force a faction to claim an area >

**Comment by ToberoCat** [comment]
what's faction bypass update for?

**Comment by RadiantSoul** [comment]
> what's faction bypass update for?

fixed the text not showing up

**Comment by ToberoCat** [comment]
More admin commands will be added in next build
