### ISSUE TITLE
[Bug] `/f wilderness` will never find a position to teleport

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions#210]
**Error log from console**
No errors in console.
![image](https://github.com/user-attachments/assets/aea61711-5872-41ea-a3fb-cea4ddafdc94)

**To Reproduce**
1. type `/f wilderness`
2. See in game error

**Expected behavior**

Teleport happens to a location in the world

**Version (please complete the following information):**
 - Plugin:
 - Server: 1.20.6 Paper build 148 (Also on 1.20.4)

**Comment by ToberoCat** [comment]
Fixed and will ship with next build
