### ISSUE TITLE
[Bug] Whitelisting world does not save in config after restart.

### ISSUE THREAD

**Issue by SirRidiculous4499** [ToberoCat/ImprovedFactions#225]
My attempt to whitelist another world other than the original "world" server folder did not work. I am using the PhantomWorld plugin and the world I was attempting to whitelist will not stay whitelisted after the server restarts. I've tried changing it while the server is stopped as well. The config just reverts to the original.

There is no error log

1. edit the config regarding the whitelist
2. restart server

I expected the server to exclude the faction commands on all other worlds other than sablecraftsurvival world

![Screenshot_2-10-2024_235324_games bisecthosting com](https://github.com/user-attachments/assets/455a40eb-8161-41ad-ade8-e532f05d5536)

**Version (please complete the following information):**
 - Plugin: Improved Factions 2.1.4
 - Server: Spigot 1.21

**Comment by Specifix5** [comment]
Have you tried using the latest dev build 2.3.0? https://github.com/ToberoCat/ImprovedFactions/releases

**Comment by ToberoCat** [comment]
Reverting might have occurred by a bug with the config migrator. The whitelist issues have been fixed in the latest dev build (2.3.0-dev) - So if you're still experiencing issues like that, consider migrating to the 2.3.0-dev build to resolve it
