### ISSUE TITLE
Armor Stands aren't covered by protections

### ISSUE THREAD

**Issue by PenguinTC** [ToberoCat/ImprovedFactions#238]
**Describe the bug**
Armor stands can be taken from/destroyed

**Error log from console**
none

**To Reproduce**
1. Take the stuff from the armor stand in a claimed base
2. profit

**Expected behavior**
Not be able to?

**Screenshots**
N/A

**Version (please complete the following information):**
 - Plugin: 2.3.0
 - Server: 1.21.1

**Additional context**
NONE

**Comment by ToberoCat** [comment]
There will be two armor stand config options:

`player-damage-armor-stand` and `armor-stand-manipulation`. They allow to configure the protection of armor stands
