### ISSUE TITLE
[Bug] Place holders no longer work

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions#254]
**Error log from console**
None

**To Reproduce**
Try use %faction_active_accumulation%, %faction_inactive_accumulation%, %faction_claim_upkeep_cost%

**Version (please complete the following information):**
 - Plugin: 2.3.0
 - Server: Paper 1.20.6 build 151

**Comment by ToberoCat** [comment]
Seems like the module placeholders didn't get registered properly - Will be fixed in the next build
