### ISSUE TITLE
[DevReport] Add a config option on where to display faction territory enter message

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions#67]
When entering a faction territory the title is the only option for displaying that. Action bar and chat options should be added to the config and apply server wide.

**Comment by ToberoCat** [comment]
Will bring back the /f preferences, as these allowed users to customize it to their needs.

**Comment by ToberoCat** [comment]
Added this option to the config file in the 2.1.2 build
