### ISSUE TITLE
[Suggestion] Letting console run commands

### ISSUE THREAD

**Issue by Evelyn3440** [ToberoCat/ImprovedFactions#7]
**Is your feature request related to a problem? Please describe.**
I need console commands to change the power via a skript.

**Describe the solution you'd like**
I would like it to let people use console as a way of running commands.

**Describe alternatives you've considered**
I've considered using papi only to remember I cant change it via that.

**Additional context**
None.

**Comment by ToberoCat** [comment]
Running commands in the console has been added in the 2.3.0-dev build.
If there are any commands that don't support a console counterpart, but actually should, let me know
